### ISSUE TITLE
Fix gå i Fængsel

### ISSUE THREAD

**Issue by FilipBLJensen** [claeslindhardt/Gruppe31CDIO3#100]
Man kan stadig rykke rundt på brættet, købe ejendomme osv. selvom man er røget i fængsel

**Comment by JRJ86** [comment]
![image](https://user-images.githubusercontent.com/42966158/50724133-b95f5300-10e8-11e9-91f8-aaa61bc9699c.png)

Dette er teksten før du skal ud af fængslet. Det er korrekt nok. Det eneste der mangler er at man også skal kunne købe sig ud af fængslet

**Comment by JRJ86** [comment]
![image](https://user-images.githubusercontent.com/42966158/50724143-080ced00-10e9-11e9-8103-410c82b1bc97.png)

Spilleren har nu rykket ud af fængslet selvom han ikke slog to ens eller købte sig ud af fængslet

**Comment by JRJ86** [comment]
Det skal dog også siges, at når man lander på feltet "Gå i fængsel", så rykker brikken ikke fra det forrige felt men er i fængsel på det felt han rykkede fra før han landte på "Gå i fængsel".
