### ISSUE TITLE
GUI: Stoppede med at virke, da terninger blev kastet. Der var valgt 10 felter, to spillere, 1 ternning og en bankerotgrænse på 1000.

### ISSUE THREAD

**Issue by AndreasBGJensen** [claeslindhardt/Gruppe31CDIO3#140]

**Comment by JRJ86** [comment]
Igen tror jeg fejlen ligger i at der kun blev valgt 1 terning.

**Comment by maltebp** [comment]
> Igen tror jeg fejlen ligger i at der kun blev valgt 1 terning.

Det er dét, så jeg lukker den her.
