### ISSUE TITLE
GUI: Der bliver kun vist 2 terninger, selvom at der vælges eks 3 terninger.

### ISSUE THREAD

**Issue by AndreasBGJensen** [claeslindhardt/Gruppe31CDIO3#141]

**Comment by JRJ86** [comment]
Man kan kun bruge 2 terninger i GUI. Vi skal have lavet et min og max på 2 så man ikke kan taste forkert, eller vi skal have fjernet den funktion at man skal indtaste hvor man ge terninger der kan være når der kun kan være 2.

**Comment by JacobChuaZiska** [comment]
Kan ikke ændres på, da vi har taget udgangspunkt i Matador GUI'en - Malte 
DO NOT TOUCH THE MATADOR GUI
