### ISSUE TITLE
Use case diagram

### ISSUE THREAD

**Issue by claeslindhardt** [claeslindhardt/Gruppe31CDIO3#3]

**Comment by claeslindhardt** [comment]
Eksempler på use case beskrivelser - vælg mindst én, der beskrives fully dressed

**Comment by AndreasBGJensen** [comment]
Rigtig godt

Har dog et spørgsmål :)
Giver det mening at vi punkt 4 i main flow i UseCase diagrammet omhandler Hvis man er landet i fængsel?

**Comment by JacobChuaZiska** [comment]
Godt at høre 
Det var også en besynderlig betingelse som man skal igennem som det første, men det har noget med at gøre, at hvis det er ens tur, så må man intet hvis man er i fængsel, andet end:
1. Betale for at komme ud, og dermed begynde spillet
2. Bruge et get-out-of-jail-card, og dermed begynde spillet
3. Shit man, jeg har slet ingen penge... Nå for helvede så kan jeg intet,
3.1. Næste spillers tur

Hvis man så ikke er i fængsel, så begynder man bare med punkt 6 :)
